name: avto_baraka
description: 'application for posting cars for sale'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 < 4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.3.0
  font_awesome_flutter: ^10.7.0
  dots_indicator: ^3.0.0
  material_symbols_icons: ^4.2719.3
  flutter_switch: ^0.3.2
  # flutter_phone_direct_caller: ^2.1.1
  share_plus: ^7.2.2
  flutter_dotenv: ^5.1.0
  dio: ^5.4.2+1
  flutter_localization: ^0.2.0
  multi_dropdown: ^2.1.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  get: ^4.6.6
  # flutter_osm_plugin: ^1.3.3~~
  fluttertoast: ^8.2.8
  app_settings: ^5.1.1
  #
  camera: ^0.11.0
  video_player: ^2.8.6
  image_picker: ^1.0.8
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  meta: ^1.10.0
  provider: ^6.1.2
  mask_text_input_formatter: ^2.9.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  location: ^6.0.2
  equatable: ^2.0.5
  bloc: ^8.1.4
  photo_view: ^0.15.0
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_basic_chat_bubble: ^0.2.2+3
  web_socket_channel: ^2.4.0
  sms_autofill: ^2.4.0
  permission_handler: ^11.3.1
  #  flutter_background: ^1.2.0
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0
  toastification: ^2.1.0
  win32: ^5.5.3
  typed_data: ^1.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: 'assets/loading/black.jpg'
  # android_gravity: 'fill'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/main_image/
    - assets/bank/
    - assets/loading/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
