Map data = {
  "region_id": "regionGroupValue",
  "district_id": "districtsGroupValue",
  "car_type_id": "carTypeGroupValue",
  "car_brand_id": "carBrandGroupValue",
  "car_model_id": "carModelGroupValue",
  "body_type_id": "_bodyType",
  "year": "_carYearValue",
  "engine": "_engineValue",
  "transmission__id": "_transmissionValue",
  "pulling_side_id": "_pullingSideValue",
  "mileage": "_mileageValue",
  "description": "descriptionValue",
  "type_of_fuel_id": "_typeOfFuelValue",
  "car_position": "_carPosition",
  "lat": "_currentPosition.latitude",
  "long": "_currentPosition.longitude",
  "imageFileList": [],
  "price": 1111,
  "valyuta": "UZS",
};
