// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7DutZ4rlSDjjwz2_TFaZez6aWSQJUL0',
    appId: '1:648296789232:android:04c40e6b631b3c4e2abe35',
    messagingSenderId: '648296789232',
    projectId: 'avto-baraka',
    storageBucket: 'avto-baraka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV_ny31Hs5SeaZd8e5SQqJ82ZaV9oF9Q',
    appId: '1:648296789232:ios:1e09e35d3c6d36952abe35',
    messagingSenderId: '648296789232',
    projectId: 'avto-baraka',
    storageBucket: 'avto-baraka.appspot.com',
    iosBundleId: 'com.avtobarakaBRROBB.avto-baraka',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJD3VSjV0xLJuHhFrAGixvsNkHwL4nAbk',
    appId: '1:648296789232:web:d3c3195c548d96d72abe35',
    messagingSenderId: '648296789232',
    projectId: 'avto-baraka',
    authDomain: 'avto-baraka.firebaseapp.com',
    storageBucket: 'avto-baraka.appspot.com',
    measurementId: 'G-4JQJW26L3L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfV_ny31Hs5SeaZd8e5SQqJ82ZaV9oF9Q',
    appId: '1:648296789232:ios:408b87c34477b94e2abe35',
    messagingSenderId: '648296789232',
    projectId: 'avto-baraka',
    storageBucket: 'avto-baraka.appspot.com',
    iosBundleId: 'com.avtobaraka.avtoBaraka',
  );

}